export const ADD_ELEMENT = `ADD_ELEMENT`
export const TOGGLE_ELEMENT = 'TOGGLE_ELEMENT'
export const REMOVE_ELEMENT = 'REMOVE_ELEMENT'
export const SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER'
export const TOGGLE_SHOW_MORE = 'TOGGLE_SHOW_MORE'
export const GET_SHOW_MORE = 'GET_SHOW_MORE'